version: "3"
services:
  mongo:
    container_name: mongo-container
    image: bitnami/mongodb:4.2.11
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/src/special-api-ts
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/special-api-ts/dist/
      - ./package.json:/usr/src/special-api-ts/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo